name: firebase_authentication_api
description: Firebase Authentication API
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  authentication_api:
    path: ../authentication_api
  firebase_auth: ^5.3.3

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
