name: recipewise
description: "A great way to manage your recipes"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  bloc: ^8.1.0
  equatable: ^2.0.5
  flow_builder: ^0.1.0
  flutter_bloc: ^8.1.1

  # Used to get Google icon
  font_awesome_flutter: ^10.1.0

  formz: ^0.8.0
  firebase_core: ^3.2.0

  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  meta: ^1.12.0

  # Scraping
  html: ^0.15.5
  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  bloc_test: ^9.0.0
  mocktail: ^1.0.0

  firebase_auth_platform_interface: ^7.0.5
  firebase_core_platform_interface: ^5.0.0
  plugin_platform_interface: ^2.1.7

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
