name: authentication_api
description: The interface and models for an API providing authentication
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.7

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
