name: authentication_repository
description: Repository for providing authentication
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  authentication_api:
    path: ../../providers/authentication_api
  equatable: ^2.0.7

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
